export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const BRANCH_REPOSITORY = Symbol('BRANCH_REPOSITORY');
export const PARKING_SLOT_REPOSITORY = Symbol('PARKING_SLOT_REPOSITORY');
export const RESERVATION_REPOSITORY = Symbol('RESERVATION_REPOSITORY');
export const PARKING_SESSION_REPOSITORY = Symbol('PARKING_SESSION_REPOSITORY');
export const PAYMENT_REPOSITORY = Symbol('PAYMENT_REPOSITORY');

export const SLOT_ASSIGNMENT_POLICY = Symbol('SLOT_ASSIGNMENT_POLICY');
export const PRICING_POLICY = Symbol('PRICING_POLICY');
export const RESERVATION_POLICY = Symbol('RESERVATION_POLICY');
export const PARKING_POLICY = Symbol('PARKING_POLICY');
export const PAYMENT_METHOD = Symbol('PAYMENT_METHOD');
