export const REGISTER_USER = Symbol('REGISTER_USER');
export const LOGIN_USER = Symbol('LOGIN_USER');

export const GET_OCCUPANCY_DASHBOARD = Symbol('GET_OCCUPANCY_DASHBOARD');
export const GET_REVENUE_REPORT = Symbol('GET_REVENUE_REPORT');
export const SIMULATE_BRANCH_FULL = Symbol('SIMULATE_BRANCH_FULL');

export const COMPARE_BRANCHES_OCCUPANCY = Symbol('COMPARE_BRANCHES_OCCUPANCY');
export const GET_BRANCH_AVAILABILITY = Symbol('GET_BRANCH_AVAILABILITY');
export const LIST_BRANCHES = Symbol('LIST_BRANCHES');

export const GENERATE_ENTRY_QR = Symbol('GENERATE_ENTRY_QR');
export const GENERATE_EXIT_QR = Symbol('GENERATE_EXIT_QR');
export const LIST_USER_SESSIONS = Symbol('LIST_USER_SESSIONS');
export const REGISTER_ENTRY = Symbol('REGISTER_ENTRY');
export const REGISTER_EXIT = Symbol('REGISTER_EXIT');
export const REPORT_SLOT_BLOCKED = Symbol('REPORT_SLOT_BLOCKED');

export const CALCULATE_AMOUNT = Symbol('CALCULATE_AMOUNT');
export const GET_PAYMENT = Symbol('GET_PAYMENT');
export const LIST_USER_PAYMENTS = Symbol('LIST_USER_PAYMENTS');
export const REGISTER_PAYMENT = Symbol('REGISTER_PAYMENT');

export const CANCEL_RESERVATION = Symbol('CANCEL_RESERVATION');
export const CREATE_RESERVATION = Symbol('CREATE_RESERVATION');
export const REQUEST_RESERVATION = Symbol('REQUEST_RESERVATION');
export const PROCESS_RESERVATION_REQUEST = Symbol(
  'PROCESS_RESERVATION_REQUEST',
);
export const EXPIRE_OVERDUE_RESERVATIONS = Symbol(
  'EXPIRE_OVERDUE_RESERVATIONS',
);
export const GET_RESERVATION = Symbol('GET_RESERVATION');
export const LIST_RESERVATIONS = Symbol('LIST_RESERVATIONS');
export const LIST_USER_RESERVATIONS = Symbol('LIST_USER_RESERVATIONS');

export const GET_CURRENT_USER = Symbol('GET_CURRENT_USER');
